# Generated by Django 5.1 on 2026-02-27 05:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facevotex_app', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=7)),
                ('organization_name', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('profile_pic', models.ImageField(upload_to='creator/profile/')),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comments', models.TextField()),
                ('submited_on', models.DateField(default=django.utils.timezone.now)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facevotex_app.student')),
            ],
        ),
    ]
