# Generated by Django 5.1 on 2026-03-12 08:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facevotex_app', '0003_creator_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('poll_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='not start', max_length=100)),
                ('poll_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facevotex_app.creator')),
            ],
        ),
    ]
