# Generated by Django 5.1 on 2026-03-17 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facevotex_app', '0004_poll'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('votes', models.CharField(default=0, max_length=50)),
                ('profile_pic', models.ImageField(upload_to='candidate/profile/')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facevotex_app.poll')),
            ],
        ),
    ]
