# Generated by Django 5.1 on 2026-03-20 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facevotex_app', '0005_candidates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.ImageField(upload_to='voter_faces/')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facevotex_app.candidates')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facevotex_app.poll')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facevotex_app.student')),
            ],
        ),
    ]
